name: stringee_plugin
description: The Stringee communications platform makes it easy to embed high-quality interactive video, voice, SMS, chat, and conferencing into web and mobile applications
version: 1.2.18
homepage: https://stringee.com
repository: https://github.com/stringeecom/stringee_flutter_plugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

flutter:
  plugin:
    platforms:
      android:
        package: com.stringee.stringeeflutterplugin
        pluginClass: StringeeFlutterPlugin
      ios:
        pluginClass: StringeeFlutterPlugin
